INSERT INTO cargo (id, count, name, price) VALUES (1, 100, 'Стул', 100);
INSERT INTO cargo (id, count, name, price) VALUES (2, 45, 'Стол', 120);
INSERT INTO cargo (id, count, name, price) VALUES (3, 12, 'Диван', 1000);
INSERT INTO cargo (id, count, name, price) VALUES (4, 35, 'Зеркало', 555);
INSERT INTO cargo (id, count, name, price) VALUES (5, 225, 'Дверь', 760);
INSERT INTO cargo (id, count, name, price) VALUES (6, 225, 'Дверная коробка', 1300);
INSERT INTO cargo (id, count, name, price) VALUES (7, 550, 'Дверная ручка', 340);
INSERT INTO cargo (id, count, name, price) VALUES (8, 225, 'Дверной замок', 475);
INSERT INTO cargo (id, count, name, price) VALUES (9, 40, 'Тумба', 1370);
INSERT INTO cargo (id, count, name, price) VALUES (10, 50, 'Кровать', 11500);
